"""Nə bişirim? — Neon PostgreSQL bağlantısı."""

import os
import re

import psycopg


LOCK_ID = 20260922


USERS_TABLE = """
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT PRIMARY KEY
)
"""


INGREDIENTS_TABLE = """
CREATE TABLE IF NOT EXISTS ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    name TEXT NOT NULL,
    normalized_name TEXT NOT NULL,
    UNIQUE (user_id, normalized_name)
)
"""


def convert_sql(sql):
    """
    Botun mövcud SQLite sorğularını PostgreSQL-ə uyğunlaşdırır.
    Ümumi SQLite emulyatoru deyil.
    """

    statement = sql.strip()

    normalized = " ".join(
        statement.upper().split()
    )

    if normalized.startswith(
        "CREATE TABLE IF NOT EXISTS USERS"
    ):
        return USERS_TABLE

    if normalized.startswith(
        "CREATE TABLE IF NOT EXISTS INGREDIENTS"
    ):
        return INGREDIENTS_TABLE

    if normalized == "BEGIN IMMEDIATE":
        return "SELECT 1"

    if re.match(
        r"^INSERT\s+OR\s+IGNORE\s+INTO\b",
        statement,
        re.IGNORECASE,
    ):
        statement = re.sub(
            r"^INSERT\s+OR\s+IGNORE\s+INTO\b",
            "INSERT INTO",
            statement,
            count=1,
            flags=re.IGNORECASE,
        )

        statement += " ON CONFLICT DO NOTHING"

    return statement.replace("?", "%s")


class Connection:

    def __init__(self, url):
        self.connection = psycopg.connect(
            url,
            connect_timeout=10,
            prepare_threshold=None,
        )

        self.locked = False

    def __enter__(self):
        return self

    def __exit__(
        self,
        exception_type,
        exception,
        traceback,
    ):
        try:
            if exception_type is None:
                self.connection.commit()
            else:
                self.connection.rollback()
        finally:
            self.connection.close()

        return False

    def execute(self, sql, parameters=()):
        # Mövcud səbət və geri qaytarma əməliyyatlarının
        # ardıcıllığını qorumaq üçün qısa tranzaksiyaları
        # eyni advisory lock vasitəsilə idarə edirik.

        if not self.locked:
            self.connection.execute(
                "SELECT pg_advisory_xact_lock(%s)",
                (LOCK_ID,),
            )

            self.locked = True

        converted = convert_sql(sql)

        return self.connection.execute(
            converted,
            parameters,
        )

    def rollback(self):
        self.connection.rollback()
        self.locked = False


def connect(old_sqlite_path=None):
    url = os.getenv("DATABASE_URL")

    if not url:
        raise RuntimeError(
            "DATABASE_URL tapılmadı. "
            "Neon bağlantısı qurulmayıb."
        )

    return Connection(url)