CREATE TABLE IF NOT EXISTS users (user_id BIGINT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    name TEXT NOT NULL,
    normalized_name TEXT NOT NULL,
    UNIQUE (user_id, normalized_name)
);
CREATE TABLE IF NOT EXISTS bot_sessions (
    user_id BIGINT PRIMARY KEY,
    state JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS favorite_recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    fingerprint TEXT NOT NULL,
    recipe JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, fingerprint)
);
CREATE INDEX IF NOT EXISTS favorite_recipes_user_idx
    ON favorite_recipes (user_id, created_at DESC);
CREATE TABLE IF NOT EXISTS processed_updates (
    update_id BIGINT PRIMARY KEY,
    user_id BIGINT,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
