CREATE TABLE IF NOT EXISTS shopping_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name TEXT NOT NULL,
    normalized_name TEXT NOT NULL,
    bought BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, normalized_name)
);
CREATE INDEX IF NOT EXISTS shopping_items_user_idx ON shopping_items (user_id, id);
ALTER TABLE processed_updates ADD COLUMN IF NOT EXISTS delivery_status TEXT NOT NULL DEFAULT 'completed';
CREATE INDEX IF NOT EXISTS processed_updates_user_idx ON processed_updates (user_id);
